# -*- coding: utf-8 -*-
"""ProC114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcIl1U4jvufTyZBW0s22vAoe6m8VvmK8
"""

from google.colab import files
data_to_upload = files.upload()

import numpy as np
import pandas as pd
import plotly.express as px

df = pd.read_csv('main.csv')

#Serial No.	GRE Score	TOEFL Score	University Rating	SOP	LOR	CGPA	Research	Chance of Admit

toefl_score = df['TOEFL Score'].tolist()
chances_of_admit = df['Chance of Admit '].tolist()

fig = px.scatter(x=toefl_score, y= chances_of_admit)
fig.show()

m = 1
c = 0
y = []

for x in toefl_score:
  y_value = m*x + c
  y.append(y_value)


fig = px.scatter(x = toefl_score,y = chances_of_admit)

fig.update_layout(shapes = [
                            dict(
                                type = 'line',
                                y0 = min(y),y1 = max(y),
                                x0 = min(toefl_score), x1 = max(toefl_score)
                            )
])

fig.show()

x = 250
y = m*x+c
print(f"chances of admition based on toefl score {x} is {y}")

toefl_score_array = np.array(toefl_score)
chances_of_admit_array = np.array(chances_of_admit)

m,c = np.polyfit(toefl_score_array,chances_of_admit_array,1)
y = []

for x in toefl_score_array:
  y_value = m*x + c
  y.append(y_value)


fig = px.scatter(x = toefl_score_array,y = chances_of_admit_array)

fig.update_layout(shapes = [
                            dict(
                                type = 'line',
                                y0 = min(y),y1 = max(y),
                                x0 = min(toefl_score_array), x1 = max(toefl_score_array)
                            )
])

fig.show()

print(m)
print(c)

x = 250
y = m*x+c
print(f"chances of admition based on toefl score {x} is {y}")